variable "app_name" {
  type        = string
  description = "Application name (generated by the CMP)"
  default     = "test-app"
}

variable "instance_count" {
  type    = number
  default = 2
}

variable "project_name" {
  type    = string
  default = "3-istor-cloud"
}

variable "flavor_name" {
  type    = string
  default = "m1.small"
}

variable "image_name" {
  type    = string
  default = "ubuntu-24.04-2026"
}
