variable "app_name" {
  type        = string
  description = "Application name (generated by the CMP)"
  default     = "test-app"
}

variable "instance_count" {
  type    = number
  default = 2
}

variable "project_name" {
  type    = string
  default = "3-istor-cloud"
}

variable "aws_region" {
  type    = string
  default = "eu-west-3"
}

variable "instance_type" {
  type    = string
  default = "t3.micro"
}

variable "ami_id" {
  type    = string
  default = "ami-00c71bd4d220aa22a" # Ubuntu 24.04 eu-west-3
}

variable "key_name" {
  type        = string
  description = "Nom de la paire de clés SSH existante dans AWS"
  default     = "arcl" # Basé sur arcl.pem vu dans tes fichiers
}
